services:
  tg-keeper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpn_bot
    environment:
      - ENV=production
    restart: unless-stopped
    networks:
      - postgres_postgres
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M

networks:
  postgres_postgres:
    external: true