lang_dict = {
    "EN": {
        "already_registered": "You are already registered",
        "approve": "Approve",
        "canceled": "Canceled",
        "change_user": "Change user:\nUser: {} {}\nPhone: {}\nUsername: {}",
        "choose_user": "Choose user to send message",
        "choose_user_to_change": "Choose user to change data",
        "decline": "Decline",
        "empty_contact": "Empty contact",
        "extend_subscription": "Extend subscription for {}",
        "message_sent": "Message sent",
        "new_user": "New user:\nUser: {} {}\nPhone: {}\nUsername: {}",
        "not_registered": "You are not registered",
        "old_data": "Old data for user {} ({}):\nFirstname: {}\nLastname: {}\nPhone: {}\nUsername: {}\nSubscription: {}\nPrice: {}",
        "payment_less_than_100": "Payments less than 100 RUB are not accepted",
        "registered": "You are registered. Now you should wait until admin will approve you",
        "request_from": "Request from {}: {}",
        "restart": "Restarting...",
        "send_data": "Send message with these data:\nNickname for User\nCost (100 RUB default)\nEnd date (yyyy-mm-dd format)\n'/exit' to cancel",
        "send_message_to_user": "Send message to user {} ({} {})\n/exit to stop",
        "send_next_message": "Send next message directly to admin. /exit to cancel",
        "small_error": "small error!",
        "subscribed_until": "You are subscribed until {}. Thank you!",
        "subscription_end_date": "Your subscription end date: {}.",
        "user_info": "User: {}\nSubscription: {}\nPrice: {}",
        "user_approved": "User approved with data: \nNickname: {}\nCost: {}\nEnd date: {}",
        "wait_for_approval": "Wait until admin will approve you",
        "wrong_data_format": "Wrong data format",
        "you_are_approved": "You are approved",
        "you_are_declined": "You are declined",
        "send_contact": "Send contact to admin",
    },
    "RU": {
        "already_registered": "Вы уже зарегистрированы",
        "approve": "Одобрить",
        "canceled": "Отменено",
        "change_user": "Изменить пользователя:\nПользователь: {} {}\nТелефон: {}\nИмя пользователя: {}",
        "choose_user": "Выберите пользователя для отправки сообщения",
        "choose_user_to_change": "Выберите пользователя для изменения данных",
        "decline": "Отклонить",
        "empty_contact": "Пустой контакт",
        "extend_subscription": "Продление подписки на {}",
        "message_sent": "Сообщение отправлено",
        "new_user": "Новый пользователь:\nПользователь: {} {}\nТелефон: {}\nИмя пользователя: {}",
        "not_registered": "Вы не зарегистрированы",
        "old_data": "Старые данные для пользователя {} ({}):\nИмя: {}\nФамилия: {}\nТелефон: {}\nИмя пользователя: {}\nПодписка: {}\nЦена: {}",
        "payment_less_than_100": "Платежи меньше 100 рублей не принимаются",
        "registered": "Вы зарегистрированы. Теперь вам нужно дождаться одобрения администратора",
        "request_from": "Запрос от {}: {}",
        "restart": "Перезапуск...",
        "send_data": "Отправьте сообщение с этими данными:\nИмя пользователя\nСтоимость (100 RUB по умолчанию)\nДата окончания (формат yyyy-mm-dd)\n'/exit' для отмены",
        "send_message_to_user": "Отправить сообщение пользователю {} ({} {})\n/exit для остановки",
        "send_next_message": "Отправьте следующее сообщение напрямую администратору. /exit для отмены",
        "small_error": "небольшая ошибка!",
        "subscribed_until": "Вы подписаны до {}. Спасибо!",
        "subscription_end_date": "Дата окончания вашей подписки: {}.",
        "user_info": "Пользователь: {}\nПодписка: {}\nЦена: {}",
        "user_approved": "Пользователь одобрен с данными: \nИмя пользователя: {}\nСтоимость: {}\nДата окончания: {}",
        "wait_for_approval": "Подождите, пока администратор вас одобрит",
        "wrong_data_format": "Неправильный формат данных",
        "you_are_approved": "Вы одобрены",
        "you_are_declined": "Вы отклонены",
        "send_contact": "Отправьте контакт администратору",
    },
}
